### PR TITLE
Add configure console member

### LINKED ISSUE #37: [setPerson bug] TypeError: this.instance.configure is not a function
Error points to the `setPerson` line from #33 

```es6
  setPerson(person) {
    return this.instance.configure({payload: {person}});
  }
```

I also wonder if `setPerson` should be defined in `init`.

My code is basically

```es6
import Base from 'ember-simple-auth/authenticators/base';
import { task } from 'ember-concurrency';
import { isPresent } from '@ember/utils';
import { inject as service } from '@ember/service';
//.....

export default Base.extend({
  authenticateTask: task(function * (accessToken) {
      //...
      this.set('sessionUser.userId', data.id);
      const rollbar = this.get('rollbar');
      if (isPresent(rollbar) && isPresent(data.id)) {
        try {
          rollbar.setPerson({"id": data.id, "name": data.attributes.name, "email": data.attributes["email-address"]});
        } catch(err) {
          rollbar.error('Unable to set user', err);
        }
      }
      //....
  }),
});
```

### PR DESCRIPTION
**Pull request by bf4**
Follows #33 (closes #37)

### CODE REVIEW

**Comment by paulcwatts** [comment]
This doesn't *quite* do what we might expect -- it will look for a `console.configure` method, which probably won't exist, and certainly wouldn't take the same arguments. I think what you want is this:

```js
configure: wrapConsole('log')
```

**Comment by bf4** [comment]
@paulcwatts Sure. I'm obviously not very proficient at this level of JavaScript :) And I didn't read the function carefully enough :) And forgot to test out npm link :)

**Comment by bf4** [comment]
Force pushed

**Comment by paulcwatts** [comment]
Thank you!

**Pull request merged**
